name: CI - Monorepo

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  detect-changes:
    name: Detect Changed Services
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.detect.outputs.services }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Detect changed submodules
        id: detect
        run: |
          # Get list of changed files
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BASE_SHA=${{ github.event.pull_request.base.sha }}
            HEAD_SHA=${{ github.event.pull_request.head.sha }}
          else
            BASE_SHA=${{ github.event.before }}
            HEAD_SHA=${{ github.sha }}
          fi

          # Get changed submodules
          CHANGED=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep -E '^(app-|svc-)' | cut -d'/' -f1 | sort -u | jq -R -s -c 'split("\n")[:-1]')

          echo "Changed services: $CHANGED"
          echo "services=$CHANGED" >> $GITHUB_OUTPUT

  lint-docs:
    name: Lint Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.github/markdown-link-check.json'
          use-quiet-mode: 'yes'

      - name: Validate YAML files
        run: |
          sudo apt-get install -y yamllint
          yamllint .github/ compose/ || true

  validate-structure:
    name: Validate Monorepo Structure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Verify all submodules registered
        run: |
          echo "Checking submodules..."
          git submodule status

          EXPECTED=52
          ACTUAL=$(git submodule status | wc -l)

          if [ $ACTUAL -ne $EXPECTED ]; then
            echo "❌ Expected $EXPECTED submodules, found $ACTUAL"
            exit 1
          fi

          echo "✅ All $ACTUAL submodules registered"

      - name: Verify critical files exist
        run: |
          for file in ARCHITECTURE.md DEVELOPMENT.md DEPLOYMENT.md CONTRIBUTING.md README.md; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing $file"
              exit 1
            fi
          done
          echo "✅ All critical documentation files present"

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  notify:
    name: Notify Team
    needs: [lint-docs, validate-structure, security-scan]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Slack
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "❌ CI Failed on ewh-monorepo",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "CI pipeline failed on `${{ github.repository }}`\n*Branch:* ${{ github.ref }}\n*Commit:* <${{ github.event.head_commit.url }}|${{ github.sha }}>\n*Author:* ${{ github.actor }}"
                  }
                }
              ]
            }
